#!/usr/bin/env python3
"""Generate the thin per-agent adapter files from skills/*/SKILL.md.

The skills are the only place Luna's behavior is written down. Every host
adapter is derived from them, so a skill edit can never leave one agent
running last month's instructions.

    python scripts/sync_adapters.py           # write the adapters
    python scripts/sync_adapters.py --check   # fail if anything is stale (CI)

Generates:
    commands/<name>.toml          Claude Code, Gemini CLI
    .opencode/command/<name>.md   OpenCode
    .cursor/rules/luna.mdc        Cursor  (from AGENTS.md)
    .agents/rules/luna.md         agent-rules hosts (verbatim AGENTS.md)
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"

GENERATED = "<!-- generated by scripts/sync_adapters.py from skills/{name}/SKILL.md -->"

# Held by every command, whichever host runs it. These are the invariants that
# must survive even when a host loads the .toml prompt and never sees SKILL.md.
INVARIANTS = (
    "End on a verdict, not a list of thoughts. "
    "Never invent metrics, trends, or benchmark numbers; if the user gave you "
    "no data, say so. Never claim knowledge of a ranking algorithm. Never "
    "promise virality. Audience is a solo operator: no advice that needs a "
    "department or a budget they did not mention."
)


def parse_skill(path):
    """Pull name + description out of a SKILL.md YAML frontmatter block.

    Deliberately not a YAML parser: the frontmatter is two known keys written
    by hand in this repo, and test_skills.py fails the build if one drifts.
    """
    text = path.read_text(encoding="utf-8")
    match = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not match:
        raise SystemExit(f"{path}: missing YAML frontmatter")
    block = match.group(1)

    name = re.search(r"^name:\s*(.+)$", block, re.MULTILINE)
    if not name:
        raise SystemExit(f"{path}: no name in frontmatter")

    desc = re.search(
        r"^description:\s*>?\s*\n?((?:.|\n)*?)(?=\n\w+:|\Z)",
        block,
        re.MULTILINE,
    )
    if not desc:
        raise SystemExit(f"{path}: no description in frontmatter")
    description = " ".join(desc.group(1).split())

    return name.group(1).strip(), description


def first_sentence(text, limit=110):
    """Short one-liner for the host's command menu."""
    sentence = text.split(". ")[0].rstrip(".")
    if len(sentence) > limit:
        sentence = sentence[:limit].rsplit(" ", 1)[0] + "..."
    return sentence


def toml_escape(value):
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render(name, description):
    """Everything a host needs, derived from the one source of truth."""
    summary = first_sentence(description)
    prompt = (
        f"Act as the {name} skill. {description} "
        f"Load and follow skills/{name}/SKILL.md, and luna/ for the ladder, "
        f"principles, minds, and platform notes, when the repo is available. "
        f"{INVARIANTS}"
    )
    if name == "luna":
        prompt = (
            "Switch to Luna {{args}} mode (soft/full/ruthless; default full). " + prompt
        )
    else:
        prompt += " {{args}}"

    toml = (
        f'description = "{toml_escape(summary)}"\n'
        f'prompt = "{toml_escape(prompt)}"\n'
    )
    markdown = (
        f"{GENERATED.format(name=name)}\n"
        f"---\n"
        f"description: {summary}\n"
        f"---\n\n"
        f"{prompt}\n"
    )
    return toml, markdown


def cursor_rule():
    """Cursor reads one always-on rule file. Keep it identical to AGENTS.md."""
    body = (ROOT / "AGENTS.md").read_text(encoding="utf-8")
    header = (
        "---\n"
        "description: Luna, marketing intelligence mode. Observe before you "
        "create, kill weak ideas, end on a verdict.\n"
        "globs:\n"
        "alwaysApply: true\n"
        "---\n\n"
    )
    return header + body


def main():
    check = "--check" in sys.argv
    stale = []
    written = 0

    targets = {}
    for skill in sorted(SKILLS.glob("*/SKILL.md")):
        name, description = parse_skill(skill)
        if name != skill.parent.name:
            raise SystemExit(
                f"{skill}: frontmatter name '{name}' != directory "
                f"'{skill.parent.name}'"
            )
        toml, markdown = render(name, description)
        targets[ROOT / "commands" / f"{name}.toml"] = toml
        targets[ROOT / ".opencode" / "command" / f"{name}.md"] = markdown

    targets[ROOT / ".cursor" / "rules" / "luna.mdc"] = cursor_rule()
    # Agent-rules hosts read AGENTS.md verbatim from their own path.
    targets[ROOT / ".agents" / "rules" / "luna.md"] = (ROOT / "AGENTS.md").read_text(
        encoding="utf-8"
    )

    for path, content in targets.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if check:
            stale.append(path.relative_to(ROOT).as_posix())
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written += 1

    if check:
        if stale:
            print("Stale adapters (run: python scripts/sync_adapters.py):")
            for path in stale:
                print(f"  {path}")
            return 1
        print(f"All {len(targets)} adapters in sync.")
        return 0

    print(f"{len(targets)} adapters checked, {written} written.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
